### ISSUE TITLE
Startup error: "Precondition failed: name != null"

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX.Desktop#18]
From: https://community.withsix.com/topic/246/can-t-run-sync-nor-install-mods-for-a3
[![https://gyazo.com/2273d3c97d336697d51f255e69805b33](https://i.gyazo.com/2273d3c97d336697d51f255e69805b33.png)](https://gyazo.com/2273d3c97d336697d51f255e69805b33)

**Comment by sickboy** [comment]
This is probably caused by improper invariant protection (e.g content name (and packageName) may never be null/empty).
The constructors were properly protected, however public setters weren't.

The user will probably have to purge his database..

**Comment by Sonsalt** [comment]
@sickboy  what do I need to test here ?

**Comment by sickboy** [comment]
@sonsalt the issue should be prevented in the future, for this ticket to close I would see if we can confirm with the user that a clean database solves his issue (as per my response on the forum)
