### ISSUE TITLE
Logo on active taskbar and notification missing

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX.Desktop#20]
![](https://i.gyazo.com/d8176f4f0790c591068970a172c5ce80.png)

**Comment by sickboy** [comment]
![logos](https://cloud.githubusercontent.com/assets/42661/16952655/75f2d558-4dca-11e6-910e-3dbafa27f2a3.png)

Can't reproduce so far. Can you try detach and re-attach the icon from taskbar?

**Comment by sickboy** [comment]
Windows bug / issue, not particular related to the release
